config/routes.rb
CMS::Application.routes.draw do

  #get 'dpd' => 'dpd#show'
  #get 'dellin' => 'dellin#show'

  # роуты для wysiwyg-редактора
  mount RedactorRails::Engine => '/redactor_rails'

  match 'payed', to: 'admin/acquiring#result', via: [:get, :post]

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск?
    # TODO проверить
    get "search/search"

    # backbone-каталог товаров
    post "catalog/fetch" => "content/catalogs#fetch", as: :catalog_fetch

    # backbone-каталог постов
    post "blogs/fetch" => "content/blogs#fetch", as: :blog_fetch
  end

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск
    get "search" => 'search#search', as: :search
  end

  scope '(:locale)/preorder', controller: 'content/preorder', locale: ContentRouter.locales do
    post '', action: :show, as: :preorder_form
    patch '', action: :finish, as: :preorder_finish
  end

  # корзина
  scope '(:locale)/cart', locale: ContentRouter.locales do
    # покупка товара
    post 'buy' => 'content/carts#buy', as: :cart_buy
    get 'buy' => 'content/carts#buy', as: :cart_get_buy

    # сохранение данных о товарах
    post 'update' => 'content/carts#update', as: :cart_update

    # расчет доставки
    patch 'delivery' => 'content/carts#delivery', as: :cart_delivery

    # удаление товара из корзины
    delete controller: 'content/carts', action: :remove_good, as: :cart_remove

    # предзаказ подтверждение
    #scope :preorder, controller: 'content/preorder' do
    #  patch '', action: :finish, as: :preorder_finish
    #end

    # заказ подтверждение
    scope :order, controller: 'content/order' do
      patch '', action: :finish, as: :order_finish
    end
  end

  # рут для админа
  get '/admin' => 'admin/welcome#index'

  # рут для контент-менеджера
  get '/cm' => 'cm/welcome#index', as: :cm_root


  # контент-менеджер
  namespace :cm do
    # категории постов
    resources :post_categories, path: 'blogs' do
      # посты
      get 'items', on: :member, action: :index, as: :items

      # выбор локали для правки
      get ':locale', on: :member, action: :edit, as: 'languaged'

      # сортировка
      post 'order', on: :collection, as: 'order'
    end

    # посты
    resources :posts do
      # блоки
      resources :blocks, controller: 'post_blocks' do
        get ':locale', on: :member, action: :edit, as: :languaged
        post 'order', on: :collection, as: 'order'
      end

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: :languaged
    end
  end

  # админ
  namespace :admin do
    # рут
    get '' => 'welcome#index', as: 'root'

    # дебаг шаблонов письем
    match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action', via: :get

    scope :acquiring, controller: :acquiring, as: :acquiring do
      get '', action: :index
      get '/cart', action: :card, as: :card
      get '/mac', action: :mac, as: :mac
      post '', action: :result, as: :result
    end

    # меню
    resources :menus

    # заказы, предзаказы
    resources :orders, :preorders, except: [:create, :edit, :update]

    # статусы заказов
    resources :order_statuses do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # типы доставки
    resources :delivery_types, :payment_types do
      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # категории товаров
    resources :good_categories, path: 'catalog' do
      get 'items', on: :member, action: :index, as: :items
      post 'order', on: :member, action: :order, as: :order
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # группы свойств
    resources :property_types do
      get 'items', on: :member, action: :index, as: :items
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # меню
    resources :menus do
      # элементы меню
      resources :menu_items
    end

    # свойства, языки, страницы, теги, параметры, переводы
    resources :properties, :languages, :pages, :tags, :settings, :translations do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # элементы меню, 3д-вьюхи, файлы, варианты, материалы
    resources :menu_items, :three60s, :files, :variants, :materials do
      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end

    # дизайнеры
    resources :designers do
      # товары
      resources :design_items do
        get ':locale', on: :member, action: :edit, as: 'languaged'
      end

      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end


    # товары
    resources :goods do
      # файлы
      resources :files, only: [:new, :create]

      # 3д-вьюхи
      resources :three60s, only: [:new, :create]

      # варианты
      resources :variants, only: [:new, :create]

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

  end

  # подключение языкового роутера
  LanguageRouter.reload
  unless LanguageRouter.routes.nil?
    LanguageRouter.routes.each do |r|
      get r
    end
  end


  # подключение контентного роутера
  ContentRouter.reload
  unless ContentRouter.routes.nil?
    scope "(:locale)", locale: ContentRouter.locales do
      ContentRouter.routes.each do |r|
        get r.except(:page, :applies_to, :active)
      end
    end
  end

  # редиректы товаров
  #GoodsRouter.reload
  unless GoodsRouter.routes.nil?
    GoodsRouter.routes.each do |r|
      get r[:route] => redirect(r[:redirect_to])
    end
  end


  match '*a', :to => 'content#show404', via: [:get, :post]
end

app/models/order.rb
# модель заказа.
# все лежит в одной таблице, в зависимости от текущего типа подтягиваются валидации
# и методы для текущего типа
#
# STI:
# - cart      корзина
# - preorder  предзаказ
# - robust    заказ
class Order < ActiveRecord::Base
  belongs_to :language

  belongs_to :order_status
  belongs_to :delivery_type
  belongs_to :payment_type

  belongs_to :client, autosave: true

  has_many :order_goods, autosave: true
  has_one :delivery_request

  delegate :first_name, :last_name, :email, :phone, to: :client, allow_nil: true

  validates :token, presence: true, uniqueness: true
  validates_with OrderValidator

  # товары заказа
  def items
    self.order_goods
  end

  # пропускаем ли валидации?
  def skip_validations?
    true if self.order_status == OrderStatus::Canceled.first
  end

  # имя клиента
  def full_name
    self.client.full_name if self.client.present?
  end

  # данные для расчета доставки
  def delivery_params
    self.attributes.select{|k, v| self.class.delivery_params.include?(k.to_sym)}
  end

  # поля, обязательные для расчета доставки
  def self.delivery_params
    [:country, :city, :region, :zip, :street, :street_number]
  end

  # стоимость товаров
  def items_price
    price = 0
    price += items.map(&:full_price).sum unless items.empty?
    price
  end

  # стоимость доставки
  def delivery_price
    price = 0
    if self.delivery_type.present?
      if self.delivery_type.is_cost_calc_needed?
        price += self.delivery_request.price if self.delivery_request.present?
      else
        price += self.delivery_type.price if self.delivery_type.present?
      end
    end
    price
  end

  # пока так
  def payment_price
    0
  end

  def total_price
    price = []
    price << items_price if items_price > 0
    price << delivery_price if delivery_price > 0
    price << payment_type if payment_price > 0

    price.sum
  end

  def items_quantity
    order_goods.map(&:quantity).sum
  end

  def items_weight(kilograms = false)
    weight = 0
    order_goods.each do |g|
      weight += (g.good_weight.present? ? g.good_weight : 0) * (g.quantity.present? ? g.quantity : 0)
    end

    kilograms == true ? weight.to_f / 1000 : weight
  end

  def items_volume(cubic_meters = false)
    volume = 0
    order_goods.each do |g|
      volume += (g.good_volume.present? ? g.good_volume : 0) * (g.quantity.present? ? g.quantity : 0)
    end

    cubic_meters == true ? volume.to_f / 1000000 : volume
  end

  # опции для формы заказа
  # возвращается хэш с услугами и стоимость товаров
  def options
    {
        delivery_types: DeliveryType.active.index_by(&:id).each_with_object({}) {|(key, value), hash| hash[key] = value.options },
        payment_types: PaymentType.active.index_by(&:id).each_with_object({}) { |(key, value), hash| hash[key] = value.options },
        items_price: self.items_price
    }
  end

  # полная стоимость заказа
  def full_price
    self.items_price + self.delivery_price + self.payment_price
  end

  # адрес в одну строку через запятые
  def full_address
    address = []

    address << self.zip if self.zip.present?
    address << Country[self.country].name if self.country.present?
    address << self.city if self.city.present?
    address << self.address if self.city.present?

    address.join ', '
  end

  def address
    address = []

    address << self.street if street.present?
    address << "д. " + self.street_number if street_number.present?
    address << "кв. " + self.site if site.present?

    address.join ', '
  end

  # генератор ключа корзины
  def self.token
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    (0...50).map{ o[rand(o.length)] }.join
  end
end

app/models/order/cart.rb
# модель корзины
# представляет собой STI-класс
# на первом этапе мы только проверяем доставку, нужен ли ее расчет/запрос
class Order::Cart < Order
  before_update :check_status_change
  after_update :validate_delivery

  private
  def validate_delivery
    delivery_request = self.delivery_request

    if self.delivery_type.present?
      if !delivery_request.present? or self.delivery_type != delivery_request.delivery_type or (self.delivery_params.select{ |k, v| v != ActiveSupport::JSON.decode(delivery_request.params)[k] }.present?)
        self.delivery_type.calculate(self, nil)
      end
    end
  end


  def check_status_change
  	# если тип сменился на "предзаказ" или "заказ", проставляем статус "новый"
    if type_change.present?
      if ['Order::Robust', 'Order::Preorder'].include? type
        self.order_status = OrderStatus::New.first unless self.order_status.present?
      end
    end
  end
end

app/models/order/preorder.rb
# модель предзаказа
class Order::Preorder < Order
end

app/models/order/robust.rb
# модель заказа
class Order::Robust < Order
  include OrderConcern

  validates :country, :city, :street, :street_number, :zip, :payment_type, :delivery_type, presence: true, unless: -> { self.skip_validations? }
  before_update :validate_delivery

  before_validation :set_country

  def acquiring
    params = {
        AMOUNT: total_price.to_f,
        BACKREF: id,
        DESC: '',
        ORDER: id,
        EMAIL: email,
        #RRN: '',
        #INT_REF: ''
    }

    AcquireApi.new(params)
  end

  private
  def set_country
    write_attribute(:country, :RU)
  end

  def validate_delivery
    #TODO wat?
  end
end

app/controllers/admin/orders_controller.rb
# Список и удаление заказов
class Admin::OrdersController < Admin::BaseController
  before_action :set_order, only: [:show, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order::Robust.all
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    if @order.update!(order_status: OrderStatus::Canceled.first)
      respond_to do |format|
        format.html { redirect_to admin_orders_url }
        format.json { head :no_content }
      end
    else
      redirect_to admin_orders_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order::Robust.find(params[:id])
    end
end

app/controllers/content/order_controller.rb
require 'net/http'
require 'uri'

# Контроллер заказа
class Content::OrderController < Content::BaseController
  layout 'content'

  before_action :check
  before_action :check_cart, only: [:show]
  before_action :set_order, only: [:done]

  def show
    redirect_to cart_path unless @cart.items.present?
  end

  def done
    @items = @order.items
  end

  def redirect
    @gateway_uri = url
    puts "!!!!!"
    puts @config
    puts "?????"
  end

  def finish
    cookies['_ga_sent'] = nil
    params = order_params
    params[:client] = Client.from_params params[:client]

    # STI-тип заказа, см модели
    #@cart = @cart.becomes! Order::Robust
    params[:type] = 'Order::Robust'

    params[:delivery_type] = DeliveryType.find(params[:delivery_type]) if params[:delivery_type].present?
    params[:payment_type] = PaymentType.find(params[:payment_type]) if params[:payment_type].present?


    respond_to do |format|
      if @cart.update(params)
        if @cart.payment_type.is_a? PaymentType::Card

          @config = {
            BACKREF: admin_acquiring_result_url,
            EMAIL: params[:client][:email],

            TRTYPE: 1,
            TERMINAL: 'CIS0ET14',
            MERCHANT: 'EPB3000E30001PB',
            MERCH: 'lllooch',

            MERCH_URL: 'http://www.lllooch.ru',
            TIMESTAMP: Time.now.strftime('%Y%m%d%H%M%S'),

            NONCE: '595ccd142a89a557',
            CURRENCY: '643',
            ORDER: '0' + @cart.id.to_s,
            AMOUNT: @cart.full_price
          }

          @config[:P_SIGN] = create_mac

          format.html { render action: 'redirect' }

          #req = Post.new(URI(url))
          #req.form_data = @config
          #req.basic_auth url.user, url.password if url.user
          #start(url.hostname, url.port,
          #      :use_ssl => url.scheme == 'https' ) {|http|
          #  http.request(req)
          #  format.html { redirect_to @config[:URL] }
          #}

          ##format.html { redirect_to order_payment_url }
          #format.html { redirect_to order_done_url, notice: '_order_updated_successfully' }
        else
          OrderMailer.order(@cart).deliver
          OrderMailer.notice(@cart).deliver

          cookies['_order_done'] = @cart.token
          format.html { redirect_to order_done_url, notice: '_order_updated_successfully' }
        end
      else
        format.html { render action: 'show' }
      end
    end
  end

  private
  def url
    'https://109.73.41.78:5443/cgi-bin/cgi_link'
  end

  def create_mac
    @cypher = %w(NONCE AMOUNT ORDER TIMESTAMP TRTYPE TERMINAL).map{|k| str = @config[k.to_sym]; [str.to_s.mb_chars.length, str].join}.join

    key = '0732D0F58CFDDFCA492DE86A872D033E'
    key = key.scan(/../).map(&:hex).map(&:chr).join
    OpenSSL::HMAC.hexdigest('sha1', key, @cypher)
  end

  def check
    raise PageNotFound unless @language.is_default
  end

  def set_order
    @order = Order::Preorder.find_by_token @token
  end

  def check_cart
    redirect_to cart_path unless @cart.items.present?
  end

  def order_params
    params.require(:cart).permit([:country, :region, :city, :street, :street_number, :site, :comment, :zip, :delivery_type, :payment_type, :client => [:first_name, :last_name, :email, :phone]])
  end
end

app/controllers/order_controller.rb
class OrderController < Content::BaseController
  layout 'content'

  before_action :check
  before_action :set_token
  before_action :set_cart, only: [:show, :finish, :done]

  def done
    @items = @cart.items
  end

  def finish
    params = order_params
    params[:order_status] = OrderStatus.find_by_name "Новый"
    respond_to do |format|
      if @cart.update(params)
        OrderMailer.order(@cart).deliver
        OrderMailer.notice(@cart).deliver
        format.html { redirect_to order_done_url, notice: '_order_updated_successfully' }
      end
    end
  end

  private
    def check 
      raise PageNotFound unless @language.is_default
    end

    def set_token
      @token = cookies['_token'] ? cookies['_token'] : Cart.token
    end

    def set_cart
      @cart = Cart.find_by_key @token
    end

    def order_params
      params.require(:cart).permit([:name, :surname, :email, :phone])
    end
end

app/views/order/show.html.erb
<div class="container cart">
  <h1>
    <%= T "Предзаказ" %>
  </h1>

  <%= simple_form_for @cart, url: order_finish_path, method: :post, html: {novalidate: false} do |f| %>
    <div class="form-block">
      <h2><%= T "Персональные данные" %></h2>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label for="name">
              <%= T "Имя" %><sup>*</sup>:
            </label>

            <div class="input-wrap">
              <%= f.input_field :name, placeholder: "Введите Ваше имя", required: true %>
            </div>
          </div>
        </div>

        <div class="span2">
          <div class="form-row">
            <label for="surname">
              <%= T "Фамилия" %><sup>*</sup>:
            </label>

            <div class="input-wrap">
              <%= f.input_field :surname, placeholder: T("Введите Вашу фамилию"), required: true %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label for="email">
              <%= T "Email" %><sup>*</sup>:
            </label>

            <div class="input-wrap">
              <%= f.input_field :email, as: :email, placeholder: T("Введите Ваш Email"), required: true %>
            </div>
          </div>
        </div>

        <div class="span2">
          <div class="form-row">
            <label for="phone">
              <%= T("Телефон:") %>
            </label>
            <div class="input-wrap">
              <%= f.input_field :phone, placeholder: T("Введите Ваш телефон") %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="pull-right">
          <button class="btn">
            <%= T "Оформить" %>
          </button>
        </div>
      </div>

    </div>
  
  <% if false %>

    <div class="form-block">
      <h2>Адрес доставки</h2>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <div class="select-wrap">
              <select placeholder="Страна">
                <option>Страна</option>
              </select>
            </div>
          </div>

          <ul class="radio-group">
            <li class="text">
              Вариант доставки:
            </li>

            <li>
              <%= f.input_field :delivery_type, as: :radio_buttons, collection: DeliveryType.all %>
            </li>
          </ul>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label for="city">
              Город<sup>*</sup>:
            </label>
            <div class="input-wrap">
              <%= f.input_field :city, placeholder: "Введите Ваш город", required: true %>
            </div>
          </div>
        </div>

        <div class="span2">
          <div class="form-row">
            <label for="region">
              Регион / Область<sup>*</sup>:
            </label>
            <div class="input-wrap">
              <%= f.input_field :region, placeholder: "Enter your State / Province / Region", required: true %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label for="address">
              Адрес<sup>*</sup>:
            </label>
            <div class="input-wrap">
              <%= f.input_field :address, placeholder: "Введите Ваш адрес", required: true %>
            </div>
          </div>
        </div>

        <div class="span2">
          <div class="form-row">
            <label for="zip">
              Индекс<sup>*</sup>:
            </label>
            <div class="input-wrap">
              <%= f.input_field :zip, placeholder: "Введите Ваш индекс", required: true %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="form-block">
      <h2>Способ оплаты</h2>

      <div class="row">
        <div class="span2">
          <ul class="radio-group">
            <li>
              <%= f.input_field :payment_type, as: :radio_buttons, collection: PaymentType.all %>
            </li>
          </ul>

          <div class="form-row">
            <div class="select-wrap">
              <select name="">
                <option>MasterCard</option>
                <option>Visa</option>
              </select>
            </div>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label>
              Номер карты:
            </label>

            <ul class="text-group size-1">
              <li>
                <div class="input-wrap">
                  <%#= f.input_field :cart_number_1, placeholder: "XXXX", required: true %>
                </div>
              </li>

              <li>
                <div class="input-wrap">
                  <%#= f.input_field :cart_number_2, placeholder: "XXXX", required: true %>
                </div>
              </li>

              <li>
                <div class="input-wrap">
                  <%#= f.input_field :cart_number_3, placeholder: "XXXX", required: true %>
                </div>
              </li>

              <li>
                <div class="input-wrap">
                  <%#= f.input_field :cart_number_4, placeholder: "XXXX", required: true %>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <div class="input-wrap">
              <%#= f.input_field :cardholder, placeholder: "Имя на карте", required: true %>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label>
              Дата активности карты:
            </label>
            <ul class="text-group select-group size-2">
              <li>
                <div class="select-wrap">
                  <select placeholder="Месяц">

                  </select>
                </div>
              </li>

              <li>
                <div class="select-wrap">
                  <select placeholder="Год">
                    
                  </select>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="span2">
          <div class="form-row">
            <label>
              Код защиты:
            </label>

            <ul class="text-group size-1">
              <li>
                <div class="input-wrap">
                  <%#= f.input_field :cardholder, placeholder: "Имя на карте", required: true %>
                  <input type="text" placeholder="XXX" />
                </div>
              </li>

              <li>
                <a href="#">Что это такое?</a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="pull-right">
          <button class="btn">
            оформить
          </button>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>