config/routes.rb
CMS::Application.routes.draw do

  #get 'dpd' => 'dpd#show'
  #get 'dellin' => 'dellin#show'

  # роуты для wysiwyg-редактора
  mount RedactorRails::Engine => '/redactor_rails'

  match 'payed', to: 'admin/acquiring#result', via: [:get, :post]

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск?
    # TODO проверить
    get "search/search"

    # backbone-каталог товаров
    post "catalog/fetch" => "content/catalogs#fetch", as: :catalog_fetch

    # backbone-каталог постов
    post "blogs/fetch" => "content/blogs#fetch", as: :blog_fetch
  end

  scope "(:locale)", locale: ContentRouter.locales do
    # поиск
    get "search" => 'search#search', as: :search
  end

  scope '(:locale)/preorder', controller: 'content/preorder', locale: ContentRouter.locales do
    post '', action: :show, as: :preorder_form
    patch '', action: :finish, as: :preorder_finish
  end

  # корзина
  scope '(:locale)/cart', locale: ContentRouter.locales do
    # покупка товара
    post 'buy' => 'content/carts#buy', as: :cart_buy
    get 'buy' => 'content/carts#buy', as: :cart_get_buy

    # сохранение данных о товарах
    post 'update' => 'content/carts#update', as: :cart_update

    # расчет доставки
    patch 'delivery' => 'content/carts#delivery', as: :cart_delivery

    # удаление товара из корзины
    delete controller: 'content/carts', action: :remove_good, as: :cart_remove

    # предзаказ подтверждение
    #scope :preorder, controller: 'content/preorder' do
    #  patch '', action: :finish, as: :preorder_finish
    #end

    # заказ подтверждение
    scope :order, controller: 'content/order' do
      patch '', action: :finish, as: :order_finish
    end
  end

  # рут для админа
  get '/admin' => 'admin/welcome#index'

  # рут для контент-менеджера
  get '/cm' => 'cm/welcome#index', as: :cm_root


  # контент-менеджер
  namespace :cm do
    # категории постов
    resources :post_categories, path: 'blogs' do
      # посты
      get 'items', on: :member, action: :index, as: :items

      # выбор локали для правки
      get ':locale', on: :member, action: :edit, as: 'languaged'

      # сортировка
      post 'order', on: :collection, as: 'order'
    end

    # посты
    resources :posts do
      # блоки
      resources :blocks, controller: 'post_blocks' do
        get ':locale', on: :member, action: :edit, as: :languaged
        post 'order', on: :collection, as: 'order'
      end

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: :languaged
    end
  end

  # админ
  namespace :admin do
    # рут
    get '' => 'welcome#index', as: 'root'

    # дебаг шаблонов письем
    match 'mailer(/:action(/:id(.:format)))' => 'mailer#:action', via: :get

    scope :acquiring, controller: :acquiring, as: :acquiring do
      get '', action: :index
      get '/cart', action: :card, as: :card
      get '/mac', action: :mac, as: :mac
      post '', action: :result, as: :result
    end

    # меню
    resources :menus

    # заказы, предзаказы
    resources :orders, :preorders, except: [:create, :edit, :update]

    # статусы заказов
    resources :order_statuses do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # типы доставки
    resources :delivery_types, :payment_types do
      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # категории товаров
    resources :good_categories, path: 'catalog' do
      get 'items', on: :member, action: :index, as: :items
      post 'order', on: :member, action: :order, as: :order
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # группы свойств
    resources :property_types do
      get 'items', on: :member, action: :index, as: :items
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # меню
    resources :menus do
      # элементы меню
      resources :menu_items
    end

    # свойства, языки, страницы, теги, параметры, переводы
    resources :properties, :languages, :pages, :tags, :settings, :translations do
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

    # элементы меню, 3д-вьюхи, файлы, варианты, материалы
    resources :menu_items, :three60s, :files, :variants, :materials do
      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end

    # дизайнеры
    resources :designers do
      # товары
      resources :design_items do
        get ':locale', on: :member, action: :edit, as: 'languaged'
      end

      get ':locale', on: :member, action: :edit, as: 'languaged'
      post 'order', on: :collection, as: 'order'
    end


    # товары
    resources :goods do
      # файлы
      resources :files, only: [:new, :create]

      # 3д-вьюхи
      resources :three60s, only: [:new, :create]

      # варианты
      resources :variants, only: [:new, :create]

      post 'order', on: :collection, as: 'order'
      get ':locale', on: :member, action: :edit, as: 'languaged'
    end

  end

  # подключение языкового роутера
  LanguageRouter.reload
  unless LanguageRouter.routes.nil?
    LanguageRouter.routes.each do |r|
      get r
    end
  end


  # подключение контентного роутера
  ContentRouter.reload
  unless ContentRouter.routes.nil?
    scope "(:locale)", locale: ContentRouter.locales do
      ContentRouter.routes.each do |r|
        get r.except(:page, :applies_to, :active)
      end
    end
  end

  # редиректы товаров
  #GoodsRouter.reload
  unless GoodsRouter.routes.nil?
    GoodsRouter.routes.each do |r|
      get r[:route] => redirect(r[:redirect_to])
    end
  end


  match '*a', :to => 'content#show404', via: [:get, :post]
end

app/models/post_block.rb
# блок поста блога
class PostBlock < ActiveRecord::Base
  include MultilingualModel
  belongs_to :post

  translates :content

  default_scope { order(:weight) }

  # тип блока
  def block_type
    type.split('::').last.downcase
  end
end

app/models/post_block/embed.rb
class PostBlock::Embed < PostBlock
  validates :content, presence: true, on: :update
end

app/models/post_block/html.rb
class PostBlock::Html < PostBlock
  validates :content, presence: true, on: :update
end

app/models/post_block/picture.rb
# Блок::Картинка, STI
class PostBlock::Picture < PostBlock
  has_attached_file :picture,
                    styles: {blog: "370x370#", preview: "100x100>"},
                    default_url: "/images/:style/missing.png",
                    url: "/uploads/post_blocks/:id/:style/:basename.:extension",
                    path: ":rails_root/public/uploads/post_blocks/:id/:style/:basename.:extension"

  validates :picture, :attachment_presence => true, on: :update
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png','image/gif'], on: :update
end

app/controllers/cm/base_controller.rb
class Cm::BaseController < ApplicationController
  layout 'cm'
  helper Admin::AdminHelper

  before_action :forever_ru

  private
    def permit_params
      params.require(controller_name.singularize).permit(get_safe_params)
    end

    def forever_ru
      I18n.locale = :ru
    end
end

app/controllers/cm/post_blocks_controller.rb
# CRUD блоков поста
class Cm::PostBlocksController < Cm::BaseController
  include MultilingualController

  before_action :set_post_block, only: [:show, :edit, :update, :destroy]
  before_action :set_post, except: [:show, :order, :destroy]

  # GET /post_blocks
  # GET /post_blocks.json
  def index
    @post_blocks = PostBlock.all
  end

  # GET /post_blocks/1
  # GET /post_blocks/1.json
  def show
    @post = @post_block.post
  end

  # GET /post_blocks/new
  def new
    @post_block = PostBlock.new
  end

  # GET /post_blocks/1/edit
  def edit
  end

  # POST /post_blocks
  # POST /post_blocks.json
  def create
    @post_block = PostBlock.new(post_block_params)
    # ставим блок в самый конец поста
    @post_block.weight = @post.blocks.size

    respond_to do |format|
      if @post_block.save
        format.html { redirect_to edit_cm_post_block_url(@post, @post_block), notice: 'Post block was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post_block }
      else
        @errors = @post_block.errors
        abort @errors.to_s
        format.html { render action: 'new' }
        format.json { render json: @post_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_blocks/1
  # PATCH/PUT /post_blocks/1.json
  def update
    respond_to do |format|
      if @post_block.update(post_block_params)
        format.html { redirect_to url_for(controller: 'cm/post_blocks', action: :index, post_id: @post.id), notice: 'Post block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post_block.errors, status: :unprocessable_entity }
      end
    end
  end

  def order
    errors = []

    if order_params
      order_params.each_with_index do |id, weight|
        post_block = PostBlock.find id
        post_block.weight = weight

        unless post_block.save :validate => false
          errors << post_block.errors
        end
      end
    end

    respond_to do |format|
      if errors.empty?
        format.json { head :no_content }
      else
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_blocks/1
  # DELETE /post_blocks/1.json
  def destroy
    post = @post_block.post
    @post_block.destroy
    respond_to do |format|
      format.html { redirect_to url_for(controller: 'cm/post_blocks', action: :index, post_id: post.id) }
      format.json { head :no_content }
    end
  end

  private
    def set_post_block
      @post_block = PostBlock.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def safe_params
      [:type, :post_id, :picture, :content]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_block_params
      permit_params
    end

    def order_params
      params.require(:order)
    end
end

app/controllers/cm/post_categories_controller.rb
# CRUD категорий постов
class Cm::PostCategoriesController < Cm::BaseController
  include MultilingualController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @collections = PostCategory.all
    @items = Post.all

    if params[:id]
      @collection = PostCategory.find(params[:id])
      
      @items = @collection.posts
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = PostCategory.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = PostCategory.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to cm_post_categories_url, notice: 'PostCategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to cm_post_categories_url, notice: 'PostCategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def order
    errors = []

    if order_params
      order_params.each_with_index do |id, weight|
        item = PostCategory.find id
        item.weight = weight

        unless item.save :validate => false
          errors << item.errors
        end
      end
    end

    respond_to do |format|
      if errors.empty?
        format.json { head :no_content }
      else
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to cm_post_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = PostCategory.find(params[:id])
    end

    def safe_params
      [:name, :slug, :parent_id, :title, :heading, :keywords, :description]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_category_params
      category_params
    end

    def category_params
      permit_params
    end

    def order_params
      params.require(:order)
    end
end

app/controllers/cm/posts_controller.rb
class Cm::PostsController < Cm::BaseController
  include MultilingualController
  
  before_action :set_post, only: [:show, :edit, :update, :destroy, :blocks]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.weight = Post.all.size

    respond_to do |format|
      if @post.save
        format.html { redirect_to cm_post_categories_url, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to cm_post_categories_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def order
    errors = []

    if order_params
      order_params.each_with_index do |id, weight|
        post = Post.find id
        post.weight = weight

        unless post.save :validate => false
          errors << post.errors
        end
      end
    end

    respond_to do |format|
      if errors.empty?
        format.json { head :no_content }
      else
        format.json { render json: errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to cm_post_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def safe_params
      [:announce, :blog_color_id, :publish, :name, :title, :heading, :keywords, :description, :content, :picture, :post_category_ids => []]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      permit_params
    end

    def order_params
      params.require(:order)
    end
end

app/controllers/cm/welcome_controller.rb
class Cm::WelcomeController < Cm::BaseController
  def index
  end
end

app/views/cm/post_blocks/_form.html.erb
<%= language_prompt %>

<%= simple_form_for [:cm, @post_block],
                    html: { class: 'form-horizontal', multipart: true },
                    url: url_for(controller: 'cm/post_blocks', action: :update, post_id: @post.id, id: @post_block.id) do |b| %>

  <% simple_fields_for 'post_block', b.object do |f| %>
      <%= form_errors f %>

      <% if 'html' == @post_block.block_type %>
        <% Globalize.with_locale(@locale.slug) do %>
          <%= f.input :content, as: :html %>
        <% end %>

        <%= language_input f %>
      <% elsif 'embed' == @post_block.block_type %>
        <% Globalize.with_locale(@locale.slug) do %>
            <%= f.input :content, as: :text %>
        <% end %>

        <%= language_input f %>
      <% else %>
        <%= image_field @post_block, :picture, f, [100, 100] %>
      <% end %>


      <div class="form-actions">
        <%= f.button :submit, save_or_update(@post_block), :class => 'btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    cm_post_blocks_path(@post), :class => 'btn' %>
      </div>

  <% end %>
<% end %>

app/views/cm/post_blocks/edit.html.erb
<div class="page-header">
  <%= language_select unless @post_block.block_type == 'picture' %>
  <h1>Правка блока: <%= @post_block.block_type %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cm/post_blocks/index.html.erb
<div class="page-header">
  <h1><%= @post.name %></h1>
</div>

<%= tabs [[:main, 'Основное', {active: false, path: edit_cm_post_path(@post, anchor: :main)}],
          [:picture, 'Обложка', {active: false, path: edit_cm_post_path(@post, anchor: :picture)}],
          [:meta, 'META', {active: false, path: edit_cm_post_path(@post, anchor: :meta)}], [:content, 'Контент', {active: true}]] %>

<% if @post.blocks.present? %>
  <div data-type="nested" data-nested-url="<%= order_cm_post_blocks_path(@post) %>">
    <% @post.blocks.each do |b| %>
        <div class="well" data-nested="item" data-nested-id="<%= b.id %>" data-toggle="collapse" data-target="#block<%= b.id %>">
          <div class="pull-right">
            <%= link_to pencil_icon,
                        edit_cm_post_block_path(@post, b.id),
                        :class => 'btn btn-mini' %>

            <%= link_to trash_icon(true),
                        cm_post_block_path(@post, b.id),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          </div>

          <div style="margin: -15px -13px 7px"><span class="label label-inverse"><%= b.block_type %></span></div>

          <div class="collapse" id="block<%= b.id %>" style="display: block; min-height: 30px">
              <% if 'picture' == b.block_type %>
                <%= image_tag b.picture.url(:preview) %>
              <% else %>
                  <%= b.content.html_safe if b.content %>
              <% end %>
          </div>
        </div>
    <% end %>
  </div>
<% else %>
    <div class="well">
      Пусто..
    </div>
<% end %>

<div class="pull-left">
  <%= simple_form_for PostBlock::Html.new(post: @post), url: url_for(controller: 'cm/post_blocks', action: :create, post_id: @post) do |b| %>
      <% simple_fields_for 'post_block', b.object do |f| %>
          <%= f.input :type, as: :hidden %>
          <%= f.association :post, as: :hidden %>

          <%= f.button :button, (content_tag(:i, '', class: 'icon icon-list-alt') + ' Контент').html_safe, :class => 'btn' %>&nbsp;
      <% end %>
  <% end %>
</div>

<div class="pull-left">
  <%= simple_form_for PostBlock::Picture.new(post: @post), url: url_for(controller: 'cm/post_blocks', action: :create, post_id: @post) do |b| %>
      <% simple_fields_for 'post_block', b.object do |f| %>
          <%= f.input :type, as: :hidden %>
          <%= f.association :post, as: :hidden %>

          <%= f.button :button, (content_tag(:i, '', class: 'icon icon-picture') + ' Фото').html_safe, :class => 'btn' %>&nbsp;
      <% end %>
  <% end %>

</div>

<div class="pull-left">
  <%= simple_form_for PostBlock::Embed.new(post: @post), url: url_for(controller: 'cm/post_blocks', action: :create, post_id: @post) do |b| %>
      <% simple_fields_for 'post_block', b.object do |f| %>
          <%= f.input :type, as: :hidden %>
          <%= f.association :post, as: :hidden %>

          <%= f.button :button, (content_tag(:i, '', class: 'icon icon-film') + ' Видео').html_safe, :class => 'btn' %>&nbsp;
      <% end %>
  <% end %>
</div>

app/views/cm/post_blocks/new.html.erb
<%- model_class = PostBlock -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/cm/post_blocks/show.html.erb
<div class="page-header">
  <h1>
   Блоки контента
  </h1>
</div>